import pandas as pd
df = pd.read_csv("C:\\Users\\sahuj\\Downloads\\HR_Project\\WA_Fn-UseC_-HR-Employee-Attrition.csv")
print(df.head())            
print("\n--- Data ki Shape ---")
print(df.shape)
print("\n--- Columns ke Naam ---")
print(df.columns)
print("\n--- Missing Values Check ---")
print(df.isnull().sum())
print("\n--- Attrition Count ---")
print(df['Attrition'].value_counts())
print("\n--- Salary Comparison (Stayed vs Left) ---")
print(df.groupby('Attrition')['MonthlyIncome'].mean())
print("\n--- OverTime vs Attrition ---")
print(pd.crosstab(df['OverTime'], df['Attrition']))
print("\n--- Department vs Attrition ---")
print(pd.crosstab(df['Department'], df['Attrition']))
df.to_csv("Cleaned_HR_Data_For_PowerBI.csv", index=False)
print("\n: Export Complete!")
